### ISSUE TITLE
Use change-to when edited

### ISSUE THREAD

**Issue by mattprecious** [Vankka/pr-target-branch-action#1]
I'd like to still execute the change-to when a PR target is edited, but the existing code [overrides](https://github.com/Vankka/pr-target-branch-action/blob/8d48815898310f5b5168234e05400d9509d0f8cc/main.js#L56) the value and then [fails](https://github.com/Vankka/pr-target-branch-action/blob/8d48815898310f5b5168234e05400d9509d0f8cc/main.js#L229).

**Comment by Vankka** [comment]
Not sure why I decided to disable those for edits, pushed the commit above.

You should be able to use `uses: Vankka/pr-target-branch-action@a0be66ab1b04dca3a50e8c9cdb4e64aa1649fc80` (a0be66ab1b04dca3a50e8c9cdb4e64aa1649fc80) for now until I get around to pushing a new version

**Comment by mattprecious** [comment]
Thanks!

**Comment by Vankka** [comment]
Available in https://github.com/Vankka/pr-target-branch-action/releases/tag/v2.1
