### ISSUE TITLE
Use NodeJS 16 instead of 12

### ISSUE THREAD

**Issue by derklaro** [Vankka/pr-target-branch-action#2]
Hi,
we're using the action in one of our repositories and since GitHub [announced](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) that they are deprecating workflows running on node 16 we're getting a deprecation warning when using this action (and in the future the action might fail to run).

It would be nice if you could push out a change to let this action use NodeJS 16 instead of 12 (which shouldn't make a difference) to prevent that deprecation message.

Thanks!

**Comment by Vankka** [comment]
Fixed in `v2.1` https://github.com/Vankka/pr-target-branch-action/releases/tag/v2.1
